### ISSUE TITLE
Can't setup Toolbelt on Windows 10

### ISSUE THREAD

**Issue by Svrkota-S** [cloud66-oss/cx#77]
I'm having trouble setting up Toolbelt on Windows 10.
I downloaded `.exe` file from: https://app.cloud66.com/toolbelt
Quickstart (https://help.cloud66.com/maestro/quickstarts/using-cloud66-toolbelt.html#install-toolbelt) says to add the PATH to the folder to the environment variables which I did and then it says to run `cx stacks list` in order to link my Cloud 66 account, but I get the following error:

`2019/05/29 13:48:24 open C:\Users\user\.cloud66\cxprofiles.json: The system cannot find the path specified.`

I couldn't find anything about this error anywhere.

**Comment by Svrkota-S** [comment]
Hello @khash, I saw a commit that you made yesterday:

https://github.com/cloud66-oss/cx/commit/eb73dc5588c1cfa984172952213652e540e6199c

Is this maybe supposed to be fix for my problem?

**Comment by khash** [comment]
Hi @Svrkota-S We don't run tests on Windows yet but a small change was made yesterday to improve the way the files are created. Could you please check to see if it helps?

**Comment by Svrkota-S** [comment]
@khash, I downloaded latest `.exe` file from the website, but I'm still getting the same error.
Did you update `.exe` file?
I mean this one:

https://app.cloud66.com/toolbelt/win

**Comment by khash** [comment]
All platform executables get updated with each release. Could you tell me your cx version please? `cx version`

**Comment by Svrkota-S** [comment]
@khash 
I get the same error for `cx version` command.
Do you want to get on a live session maybe to try and resolve this?
I think it would be easier.

**Comment by khash** [comment]
Hi @Svrkota-S I've just pushed `0.1.74` with a potential fix.

**Comment by Svrkota-S** [comment]
@khash 

I still get `0.1.72` when I try to download from https://app.cloud66.com/toolbelt/win

**Comment by khash** [comment]
Apologies about that. It should be the latest version now

**Comment by Svrkota-S** [comment]
@khash 

Working like a charm!
Thanks, closing this now.
